---
- hosts: ios01
  gather_facts: false

  tasks:
    - name: gathered
      cisco.ios.ios_l3_interfaces:
        state: gathered
      register: gather_result

    - name: current config rendered
      cisco.ios.ios_l3_interfaces:
        config: "{{ gather_result['gathered']  }}"
        state: rendered
      register: current_config

    - name: asumed config rendered
      cisco.ios.ios_l3_interfaces:
        config: "{{ l3_interfaces }}"
        state: rendered
      register: assumed_config

    - name: fact_diff
      ansible.builtin.import_role:
        name: fact_diff
