---
- name: ios facts 
  ansible.builtin.import_tasks: ios_facts.yml
  when: ansible_network_os == 'ios'

- name: iosxr facts 
  ansible.builtin.import_tasks: iosxr_facts.yml
  when: ansible_network_os == 'iosxr'

- name: nxos facts 
  ansible.builtin.import_tasks: nxos_facts.yml
  when: ansible_network_os == 'nxos'